brot3ncm_desc="Experimental Medium Rapid Assault Mech"
brot3ncm_help="Experimental Medium Rapid Assault Mech"
brot3ncm_name="Eliash"
ual0401_desc="Experimental Heavy Assault Bot"
ual0401_help="Experimental Heavy Assault Bot"
ual0401_name="Galactic Colossus"
wal0401_desc="Experimental Ultra Heavy Assault Bot"
wal0401_help="Experimental Ultra Heavy Assault Bot"
wal0401_name="Universal Colossus"
bel0402_desc="Experimental Ultra Heavy Breacher Bot"
bel0402_help="Experimental Ultra Heavy Breacher Bot"
bel0402_name="Goliath"


uvd_0017="Transport Speed Reduction: %.3g"