Description['brot3ncm']	= "The Eliash Experimental Rapid Assault Mech represents the pinnacle of hit-and-run tactics, designed to strike swiftly and retreat before sustaining significant damage. It boasts the most advanced shield regeneration capabilities across all factions, a testament to the Eliash's superior shield technology. The Aeon is armed with formidable anti-aircraft weaponry and the infamous Tosis Weapon, an immensely powerful green beam that deals massive damage to large targets. This is further complemented by blue laser arrays, perfect for shredding smaller enemies with precision. The Aeon’s unique combination of speed, agility, and advanced weaponry makes it a fearsome asset on the battlefield, embodying the ultimate in rapid assault tactics."

-- Unit Upgrades Descriptions --
Description['zrb9601-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zrb9601-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zrb9601-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zrb9601-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zrb9601-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['zrb9601-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zrb9601'] = "Constructs Tech 3 land units. Highest tech level available.\n\nProduction Enhancements available."

Description['zeb9601-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zeb9601-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zeb9601-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zeb9601-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zeb9601-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['zeb9601-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zeb9601'] = "Constructs Tech 3 land units. Highest tech level available.\n\nProduction Enhancements available."

Description['zab9601-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zab9601-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zab9601-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zab9601-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zab9601-Materiel_Exp'] = "This enhancement reduces material usage by 25% and energy maintenance drain by 20%.\nThe health of the structure is increased by 33% over the base amount."
Description['zab9601-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['zab9601-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zab9601'] = "Constructs Tech 3 land units. Highest tech level available.\n\nProduction Enhancements available."

Description['zsb9601-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zsb9601-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zsb9601-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zsb9601-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zsb9601-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['zsb9601-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zsb9601'] = "Constructs Tech 3 land units. Highest tech level available.\n\nProduction Enhancements available."

Description['zrb9602-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zrb9602-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zrb9602-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zrb9602-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zrb9602-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['zrb9602-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zrb9602'] = "Constructs Tech 3 air units. Highest tech level available.\n\nProduction Enhancements available."

Description['zeb9602-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zeb9602-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zeb9602-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zeb9602-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zeb9602-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['zeb9602-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zeb9602'] = "Constructs Tech 3 air units. Highest tech level available.\n\nProduction Enhancements available."

Description['zab9602-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zab9602-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zab9602-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zab9602-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zab9602-Materiel_Exp'] = "This enhancement reduces material usage by 25% and energy maintenance drain by 20%.\nThe health of the structure is increased by 33% over the base amount."
Description['zab9602-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['zab9602-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zab9602'] = "Constructs Tech 3 air units. Highest tech level available.\n\nProduction Enhancements available."

Description['zsb9602-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zsb9602-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zsb9602-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zsb9602-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zsb9602-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['zsb9602-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zsb9602'] = "Constructs Tech 3 air units. Highest tech level available.\n\nProduction Enhancements available."

Description['zrb9603-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zrb9603-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zrb9603-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zrb9603-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zrb9603-Sonar_T3'] = "Installs a typical T3 sonar package onto the factory."
Description['zrb9603-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zrb9603'] = "Constructs Tech 3 naval units. Highest tech level available.\n\nProduction Enhancements available."

Description['zeb9603-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zeb9603-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zeb9603-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zeb9603-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zeb9603-Sonar_T3'] = "Installs a typical T3 sonar package onto the factory."
Description['zeb9603-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zeb9603'] = "Constructs Tech 3 naval units. Highest tech level available.\n\nProduction Enhancements available."

Description['zab9603-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zab9603-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zab9603-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zab9603-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zab9603-Materiel_Exp'] = "This enhancement reduces material usage by 25% and energy maintenance drain by 20%.\nThe health of the structure is increased by 33% over the base amount."
Description['zab9603-Sonar_T3'] = "Installs a typical T3 sonar package onto the factory."
Description['zab9603-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zab9603'] = "Constructs Tech 3 naval units. Highest tech level available.\n\nProduction Enhancements available."

Description['zsb9603-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['zsb9603-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['zsb9603-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['zsb9603-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['zsb9603-Sonar_T3'] = "Installs a typical T3 sonar package onto the factory."
Description['zsb9603-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['zsb9603'] = "Constructs Tech 3 naval units. Highest tech level available.\n\nProduction Enhancements available."